# Generated by Django 2.2.3 on 2019-07-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inchikey', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('smiles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recepteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.CharField(max_length=1000)),
                ('espece', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_affinite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EC50', models.FloatField(blank=True, default=None, null=True)),
                ('ref', models.CharField(max_length=255)),
                ('id_legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phandlers.Ligend')),
                ('id_recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phandlers.Recepteur')),
            ],
        ),
    ]
